name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x   
    - name: Install Nuget
      uses: warrenbuckley/Setup-Nuget@v1
      
    - name: Restore dependencies
      run: |
        nuget sources add -name "private-packages" -Source https://nuget.pkg.github.com/peace920902/index.json -StorePasswordInClearText -Username peace920902 -Password ${env:Password}
        dotnet restore
      env: 
        Password: ${{ secrets.PACKAGE_TOKEN }}
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --no-build
    - name: docker build
      run: docker build . -t ci
