name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x 
    - name: Restore dependencies
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/peace920902/index.json -n "private-packages" --store-password-in-clear-text -u peace920902 -p ${{ secrets.PACKAGE_TOKEN }}
        dotnet restore      
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --no-build
    - name: docker build
      run: docker build . -t ci
    - name: docker login
      run: docker login -u peace920902 -p ${{ secrets.PACKAGE_TOKEN_RW }}
    - name: docker push
      run: docker push ghcr.io/peace920902/ci:latest
    
