name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x   
    
    - name: Restore dependencies
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/peace920902/index.json --name "private-packages"  -StorePasswordInClearText --username peace920902 --password ${env:Password}
        dotnet restore
      env: 
        Password: ${{ secrets.PACKAGE_TOKEN }}
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -c Release --no-build
    - name: docker build
      run: docker build . -t ci
